This is makeindex, version 2.15 [TeX Live 2018] (kpathsea + Thai support).
Scanning style file ./main_SimpleHeader.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file main_SimpleHeader.acn....done (1 entries accepted, 0 rejected).
Sorting entries...done (0 comparisons).
Generating output file main_SimpleHeader.acr....done (6 lines written, 0 warnings).
Output written in main_SimpleHeader.acr.
Transcript written in main_SimpleHeader.alg.
