This is makeindex, version 2.15 [TeX Live 2018] (kpathsea + Thai support).
Scanning style file ./main_Web.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file main_Web.acn....done (15 entries accepted, 0 rejected).
Sorting entries....done (54 comparisons).
Generating output file main_Web.acr....done (16 lines written, 0 warnings).
Output written in main_Web.acr.
Transcript written in main_Web.alg.
